### ISSUE TITLE
Frequent apprunner deadlocks in 3.1 on Stretch since ~2016-12-12

### ISSUE THREAD

**Issue by fastcat** [tiliado/nuvolaplayer#279]
Since I updated nuvolaplayer3 ~ December 12th (I think, might have been the Monday before), I'm experiencing frequent "deadlocks" of sorts in all three web apps I use: google_play_music, google_calendar, google_keep (local creation cargo cult'd off an older version of google_calendar, see #222).

When it deadlocks, the top level window controls (e.g. the gear icon) still respond, but the WebKit frame is frozen and is unresponsive to keyboard or mouse input.  Moving the mouse across elements does not change the mouse cursor, resizing the window does not redraw content, sometimes animations are visibly frozen mid-animate.

If one app freezes like this, other apps generally continue on OK (unless they too freeze).  I can kill an individual apprunner instance without disrupting the other apps and restart it in this case.

Curiously, in the case of GPM, the current song will finish playing in this case (I guess flash can do this without interacting with the rest of the system) but new songs won't play after (not surprising if the JS is locked up).

Every now and then this 'deadlock' will actually happen at startup -- the app will never load.  Occasionally it will load after a minute or two of waiting, but other times it may stay frozen for _hours_.  I've seen the 'runtime' freeze stuck for hours frequently (this is particularly noticeable in Google Calendar with the red line representing now -- very easy to see when it locked up).

I typically have all three apps mentioned above running, but I've seen this happen with each of them running by themselves.  I haven't noticed any particular pattern (yet) as to when it locks up.  Thus far it seems pretty random.

I currently have nuvolaplayer3(-core) `3.1.1~201612051252.ed9ae72-0+1~sid` from the tiliado repo and `libwebkit2gtk-4.0-37-gtk2` `2.14.2-1` from Debian Stretch/Sid on x86_64, standard Gnome desktop environment.

I'm collecting a fresh debug log now to help investigate, will note here once I've hit it again

**Comment by fastcat** [comment]
I have a debug log captured but ... there are no messages from when it deadlocked.  I can still share it if needed, though I'd prefer to do so privately (let me know how) since the log has what look like potentially sensitive tokens.

**Comment by fenryxo** [comment]
Hello @fastcat. Thanks for taking the time to report this issue. I need more information to investigate it further.

It looks there is a deadlock or crash in the WebKitWebProcess. It is necessary to find out whether is crashed or there is a deadlock.

1. Enable core dumps: `ulimit -c unlimited`
2. Run Nuvola Player from a terminal: `nuvolaplayer3 -D`
3. Once the issue appears, kill all Nuvola Player processes.
4. Check whether there is a core dump file: `ls -lh core*`
5. If so, try to get a backtrace with gdb:
    ```
    $ gdb /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess core
    (gdb) bt
    ...
    (gdb) quit
    ```
6. Send the console output & backtrace to janousek.jiri@gmail.com

**Comment by fenryxo** [comment]
Although I wasn't able to reproduce this issue on Debian Jessie with system libraries, it was reproducible in a flatpak build with the latest GNOME platform. I should be fixed now. Could you test the latest build I've just published?

**Comment by fastcat** [comment]
Thank you 👍  -- New build has run all day with all three apps going and nary a hang amongst them

**Comment by fastcat** [comment]
Oops, I spoke carelessly ... calendar and music are OK, but keep seems to have hung somehow.  It's vastly improved at least, but something is still not 100%.

For confirmation, I'm running 3.1.1~201612311655.0856fd7-0+1~sid now

**Comment by fastcat** [comment]
Would it be useful for me to force a core dump of one or more of the processes while in the hung state (e.g. with kill -ABRT) for inspection?

**Comment by fenryxo** [comment]
> Would it be useful for me to force a core dump of one or more of the processes while in the hung state (e.g. with kill -ABRT) for inspection?

Yes, that's a great idea :-)

**Comment by fastcat** [comment]
I've collected cores for all four processes (nuvolaplayer3 + 1x responsive apprunner + 2x hung apprunner) and e-mailed the backtrace info to the address above.  I've retained the cores so if there is additional info you would like me to extract from them (print locals etc from various frames) let me know.  I'm familiar with GDB and C/++, but not with the glib/gtk/webkit code specifically.

**Comment by fastcat** [comment]
Here's a "fun" tidbit:

I just noticed google_play_music was hung (while paused) ... except that clicking the play button caused it to start playing!  Clicking it again doesn't pause it though, nor does it respond to MPRIS or nuvolaplayer3ctl pause commands.

**Comment by fenryxo** [comment]
I've finished setting up [a clean sand-boxed development environment](https://github.com/tiliado/nuvolaplayer/wiki/Nuvola-Core-Developer-Kit) with the latest stable GNOME libraries. That allows me to look into this issue deeper and hopefully to fix it. Thanks for your patience.

**Comment by fastcat** [comment]
I haven't had a chance to capture new more complete sets of core files (I use this mostly at work and work has been ... nuts), but I did notice an interesting behavior related to this recently:

If I happen to catch it just as it is first "freezing", resizing the window (specifically sending my Gnome hotkey to maximize the window) will "unfreeze" it.

Also noticed that at least the Google Music one seems to freeze a lot less if I leave it minimized and interact just through global hotkeys / MPRIS.

**Comment by fenryxo** [comment]
Hello @fastcat. I might have found the cause of the issue. Could you test the latest build of both Diorite library & Nuvola Player 3.1? Thanks.

**Comment by fastcat** [comment]
Will do -- when I'm back in the office (where I tend to hit this) on Wednesday.

**Comment by fastcat** [comment]
So far so good 👍 

Of course, at the same time a system update to webkit has broken rendering of one of my apps, but that's not your fault ☺️️

**Comment by fastcat** [comment]
Just an extra note -- I hadn't used nuvolaplayer so much yesterday, but I've been using it much more today, and still good!

**Comment by fenryxo** [comment]
Great! Could you test also [Flatpak builds](https://github.com/tiliado/nuvolaplayer/wiki/Flatpaks)? I'm going to deprecate DEB packages for Debian later this month (mainly because Jessie has so ancient libs and Debian don't provide any security support to WebKitGTK).

**Comment by fenryxo** [comment]
FYI, Google Calendar flatpak is also available in the same repo.

**Comment by fenryxo** [comment]
[Nuvola Player 3.0.5 and Diorite 0.2.2 has been released.](https://medium.com/nuvola-news/nuvola-player-3-0-5-and-diorite-0-2-2-released-c170dfb53130)
